/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_FILES           2
#define MMAP_ASSETS_CHECKSUM        0x22EE

enum MMAP_ASSETS_LISTS {
    MMAP_ASSETS_ANIM_360_360_BIN = 0,        /*!< anim_360_360.bin */
    MMAP_ASSETS_ASSETS_ECHOEAR_BIN = 1,        /*!< assets_echoear.bin */
};
